env:
  node: true
  mocha: true

parser: "babel-eslint"
parserOptions:
  ecmaVersion: 6
  jsx: true

rules:
  brace-style: [2, "1tbs"]
  camelcase: 0
  comma-style: [2, "last"]
  consistent-return: 0
  default-case: 2
  dot-notation: 0
  eqeqeq: 0
  func-style: 0
  handle-callback-err: [2, "^(err|error|anySpecificError)$" ]
  key-spacing: 0
  quotes: [2, "single", "avoid-escape"]
  new-cap: 0
  no-use-before-define: [2, "nofunc"]
  no-floating-decimal: 2
  no-inner-declarations: 1
  no-loop-func: 0
  no-multi-spaces: 0
  no-nested-ternary: 2
  no-octal: 0
  no-path-concat: 1
  no-redeclare: 0
  no-return-assign: 0
  no-shadow: 0
  no-trailing-spaces: 0
  no-underscore-dangle: 0
  no-unused-vars: [2, {"vars": "all", "args": "none"}]
  space-after-function-name: [0, "never"]
  space-before-blocks: 2
  spaced-line-comment: [0, "always", { exceptions: ["-"]}]
  strict: [2, "global"]
  wrap-iife: [2, "any"]
  yoda: [2, "never", { "exceptRange": true }]
  keyword-spacing: [2, {"before": true, "after": true}]