type Query{
    users(_id: ID): [User]
    users_name(name: String): [User]
}

type User {
    _id: ID!
    name: String!
    full_name: String
    age: Int
    city: String
    tag: String
    url: String
    knowledge: [Knowledge]
}

type Knowledge {
    language: String
    frameworks: [String]
}
