type Query {
    users(_id: ID, name: String): [User]
}

type Mutation {
    createUser(user: UserInput!): User
    updateUser(_id: ID!, user: UserInput!): User
}

type User {
    _id: ID!
    name: String!
    full_name: String
    age: Int
    city: String
    tag: String
    url: String
    knowledge: [Knowledge]
}

type Knowledge {
    language: String
    frameworks: [String]
}

input UserInput {
    name: String!
    full_name: String
    age: Int
    city: String
    tag: String
    url: String
    knowledge: [KnowledgeInput]
}

input KnowledgeInput {
    language: String
    frameworks: [String]
}
